### ISSUE TITLE
diff/patch is wrong

### ISSUE THREAD

**Issue by LeeRHuang** [mendsley/bsdiff#14]
When i use this repository,i diff and patch local successfull , but maybe you not use the right BSDIFF arithmetic，Because Android and Server (This repository https://github.com/malensek/jbsdiff) use the same text , They can diff and patch right,but iOS platform  diff binary post to server,it's wrong。

**Comment by CoolOppo** [comment]
If you would take two seconds to read the README, you would see that it isn't compatible with the original `bsdiff`:

> This library generates patches that are not compatible with the original bsdiff tool.

Also try taking a few more minutes to make some fucking sense. It's clear English isn't your first language, but it's not everybody else's job to try and understand what you are attempting to say.
