### ISSUE TITLE
VLE encoding and fix for #1

### ISSUE THREAD

**Issue by r-lyeh** [mendsley/bsdiff#5]
Hello @mendsley,

I do not think you might be interested on the following changes, but if you are just drop me a line and I will create one or two pretty pull requests for these : )

a) breaking change
I have replaced the fixed bucket size of [8*3] bytes for patches as seen in `offtin` and `offtout` functions to a variable length encoding that can take from 1 to 10 bytes for each 64-bit signed integer encoded. That makes a range from 3 bytes (best case) to 30 bytes (worst case) instead of a 24-bytes fixed case.

Pros:
- smaller patches to the wire, which is more important to me. 

Cons:
- patches are not backwards compatible anymore (neither with bsdiff tool).
- someway slower (overhead from 3 to 30 callback calls instead of a single call of 24 bytes)

b) fix for #1
I have applied the solution as seen on [this thread](http://stackoverflow.com/questions/12751775/why-does-bsdiff-exe-have-trouble-with-this-smaller-file)

Pros:
- It seems to work.

Cons:
- it would need some more (real) extensive testing and/or proper unit testing to see I did not break it.
- the license for SAIS is MIT instead of BSD-2 :/

Happy new year btw,
- r-lyeh

**Comment by mendsley** [comment]
Hey @r-lyeh, if you have the changes as something that can be reviewed as a pull request, i'll look into a sane way to merging them into the mainline.
